language: node_js
node_js:
  - "8"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - node setup
  - npm run test
script: 
  - npm run test
  - gulp build
