language: node_js
node_js:
  - "8"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - npm install -g jest
  - npm install -g jest-cli
  - node setup
script: 
  - yarn test
  - gulp build
