language: node_js
node_js:
  - "8"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - node setup
script: 
  - if [ "$TRAVIS_BRANCH" = "dev" ]; then gulp test; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then gulp test && gulp build; fi