language: node_js

node_js:
  - "8"

sudo: false

branches:
   only:
   - dev

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"

before_script:
  - yarn install
  - cd sample
  - yarn install
  - cd ..
script: 
  - yarn run test
