language: node_js
node_js:
  - "8"
before_script:
  - node setup
script: 
  - if [ "$TRAVIS_BRANCH" = "dev" ]; then gulp test; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then gulp test && gulp build; fi
