language: node_js
node_js:
  - "8"
before_script:
  - node setup
script: 
  - if [ "$TRAVIS_BRANCH" = "dev" ]; then npm test; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm test && gulp build; fi
